Create an array containing 4 string elements: your first name, your last name, your birth
state and your favorite color.


In [6]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
me = make_array("Kelly", "Grier", "Colorado", "Purple")
me

array(['Kelly', 'Grier', 'Colorado', 'Purple'], dtype='<U8')

Use a numpy function to make all elements uppercase.

In [7]:
upper = np.char.upper(me)
upper

array(['KELLY', 'GRIER', 'COLORADO', 'PURPLE'], dtype='<U8')

Use a numpy function to count the number of times the letter “a” appears in each
element of your array.

In [10]:
count_a = np.char.count(me, 'a')
count_a

array([0, 0, 1, 0])

Optional: Use a numpy function to find the length of each element in the array.
You may need to Google this.

In [12]:
length = []
for i in me:
    length.append(len(i))
print(length)

[5, 5, 8, 6]


Create an array containing EVERY OTHER odd number starting with 1 and ending with
(and including) 41.

In [14]:
odds = np.arange(1,46,4)
odds

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

Use numpy to find the sum and the product of the elements of this array. NOTE:
This will require you to convert the elements of your array to floats using the
astype method.

In [15]:
sum_odds = np.sum(odds)
sum_odds

276

In [16]:
prod_odds = np.prod(odds)
prod_odds

616159193

Use numpy to take the natural log of each element.

In [17]:
ln_odds = np.log(odds)
ln_odds

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

Optional: The numpy function np.diff finds the difference between adjacent
elements of an array. Find the SUM of adjacent elements of this array.

In [20]:
sum_adjacent = odds + np.roll(odds, -1)
sum_adjacent

array([ 6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86, 46])

In [22]:
sum2 = odds[:-1] + odds[1:]
sum2

array([ 6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86])