In [6]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
me = make_array("Kelly", "Grier", "Colorado", "Purple")
me

array(['Kelly', 'Grier', 'Colorado', 'Purple'], dtype='<U8')

In [7]:
upper = np.char.upper(me)
upper

array(['KELLY', 'GRIER', 'COLORADO', 'PURPLE'], dtype='<U8')

In [10]:
count_a = np.char.count(me, 'a')
count_a

array([0, 0, 1, 0])

In [12]:
length = []
for i in me:
    length.append(len(i))
print(length)

[5, 5, 8, 6]


In [14]:
odds = np.arange(1,46,4)
odds

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

In [15]:
sum_odds = np.sum(odds)
sum_odds

276

In [16]:
prod_odds = np.prod(odds)
prod_odds

616159193

In [17]:
ln_odds = np.log(odds)
ln_odds

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

In [20]:
sum_adjacent = odds + np.roll(odds, -1)
sum_adjacent

array([ 6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86, 46])

[3, 11, 19, 27, 35, 43, 51, 59, 67, 75, 83, 91]
